import { Geist_Mono, DM_Sans } from 'next/font/google';
import Providers from './providers';
import Navbar from '@/components/common/navbar';
import ThemeScript from '@/components/common/ThemeScript';
import './globals.css';

const sans = DM_Sans({ subsets: ['latin'] });

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <ThemeScript />
      </head>
      <body className={`${sans.className} font-sans antialiased`}>
        <Providers>
          <Navbar />
          {children}
          <footer className='p-10 text-center text-gray-400'>
            © 2026 CodeHaja. All rights reserved.
          </footer>
        </Providers>
      </body>
    </html>
  );
}
