spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/code_haja_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.property-naming-strategy=SNAKE_CASE
server.port=8081
